import Head from "next/head";
import logo from "../assets/logo.png";
import Image from "next/image";

import SignIn from "./signin";

export default function Home() {
  return (
    <>
      <Head>
        <title>SystemPackage</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Image src={logo} className="w-12 m-10" alt="SystemPackage" />
        <SignIn />
      </main>
    </>
  );
}
